<?php

namespace EzPlatform\ActivitiesLogBundle\Repository;

/**
 * see lib folder.
 *
 * ActivitiesLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitiesLogRepository extends \Doctrine\ORM\EntityRepository
{
}
